version: '3'
services:
  flask_app:
    build: ./flask_app
    container_name: flask_app
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    networks:
      - app_network

networks:
  app_network:
    external: true
