version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - PC1_IP=http://flask_app:5000  # Dynamisch IP van PC 1
    depends_on:
      - flask_app
    networks:
      - app_network

  register_ip:
    build: ./register_ip  # Dit is een Python-script dat het IP van PC 1 registreert
    container_name: register_ip_script
    depends_on:
      - flask_app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
