services:
  app:
    build: .
    container_name: restapi_executor_server
    ports:
      - "80:80"
    environment:
      - HOST=0.0.0.0
      - PORT=80
      - DEBUG=true
      - API_KEY=your_secret_api_key
    restart: always
