version: "3.8"

services:
  websocket-server:
    build: ./server
    container_name: websocket-server
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./server/nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Correcte verwijzing
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    depends_on:
      - websocket-server

  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email jouw-email@example.com --agree-tos --no-eff-email --force-renewal -d parentpager.pouwertronics.nl
