version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: api-gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./www:/var/www/certbot
      - ./certbot:/etc/letsencrypt
    restart: always
    depends_on:
      - certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./www:/var/www/certbot
      - ./certbot:/etc/letsencrypt
    entrypoint: >
      sh -c "certbot certonly --webroot -w /var/www/certbot 
      --email mail@pouwertronics.nl
      --agree-tos 
      --no-eff-email 
      --force-renewal 
      -d parentpager.pouwertronics.nl"
