##
#
# Copyright (c) 2025, Lorenzo Pouw.
# All rights reserved.
#
##

services:
  restapi_executor_server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: restapi_executor_server_container
    expose:
      - "5000"
    networks:
      - app-network
    environment:
      - HOST=0.0.0.0
      - PORT=80
      - DEBUG=false
      - API_KEY=your_secret_api_key
      - SSL_CERT=path/to/ssl.cert
      - SSL_KEY=path/to/ssl.pem

  nginx:
    image: nginx:latest
    container_name: restapi_executor_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - restapi_executor_server
    networks:
      - app-network

networks:
  app-network:
