# docker-compose.yml
services:
  restapi_executor_server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: restapi_executor_server_container
    expose:
      - "5000"
    networks:
      - app-network
    environment:
      - API_KEY=your_secret_api_key

  nginx:
    image: nginx:latest
    container_name: restapi_executor_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - restapi_executor_server
    networks:
      - app-network

networks:
  app-network: