services:
  parentpager_executor_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parentpager_executor_server
    expose:
      - "5000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: parentpager_executor_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - parentpager_executor_server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
