version: '3.8'

services:
  flask_socketio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_socketio
    ports:
      - "5000:5000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
